# Generated by Django 5.1.4 on 2025-01-01 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('1', 'Asset'), ('2', 'Liability'), ('3', 'Equity'), ('4', 'Revenue'), ('5', 'Expense'), ('6', 'Gain'), ('7', 'Loss')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('guideline', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AccountLevel1',
                'verbose_name_plural': 'AccountLevel1s',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('11', 'Current Asset'), ('12', 'Fixed Asset'), ('21', 'Current Liability'), ('22', 'Long-term Liability'), ('31', 'Common Stock'), ('32', 'Preferred Stock'), ('33', 'Retained Earning'), ('41', 'Personal Revenue'), ('42', 'Corporate Revenue'), ('51', 'Personal Expense'), ('52', 'Corporate Expense')], max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('guideline', models.TextField(blank=True, null=True)),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_account', to='acc_codes.accountlevel1')),
            ],
            options={
                'verbose_name': 'AccountLevel2',
                'verbose_name_plural': 'AccountLevel2s',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('1100', 'Cash'), ('1102', 'Deposit'), ('1103', 'E-wallet'), ('1104', 'Debit Card'), ('1105', 'Account Receivable(AR)'), ('1201', 'Inventory'), ('1202', 'Equipment'), ('1203', 'Vehicle'), ('1204', 'Taxes Receivable'), ('1205', 'Accured Wage'), ('2101', 'Credit Card'), ('2102', 'Account Payable(AP)'), ('2103', 'Accured Expense'), ('2201', 'Loan'), ('2202', 'Taxes Payable'), ('3100', 'Common Stock'), ('3200', 'Preferred Stock'), ('3300', 'Retained Earning'), ('4101', 'Salary Revenue'), ('4102', 'Wage Revenue'), ('4103', 'Licensing Revenue'), ('4104', 'Interest Revenue'), ('4105', 'Rent Revenue'), ('4106', 'Business Revenue'), ('4107', 'Scholarship Stipend'), ('4108', 'Allowance'), ('4211', 'Goods'), ('4212', 'Services'), ('4213', 'Products'), ('4214', 'Subsciptions'), ('5101', 'Food Expense'), ('5102', 'Transportation Expense'), ('5103', 'Shopping Expense'), ('5104', 'Utilities Bill'), ('5105', 'Health Expense'), ('5106', 'Education Expense'), ('5107', 'Social & Recreation Expense'), ('5108', 'Family Expense'), ('5109', 'Miscellaneous Expense'), ('5110', 'Accommodation Expense'), ('5201', 'Payroll'), ('5202', 'Rent'), ('5203', 'Travel Expense'), ('5204', 'Depreciation'), ('5205', 'Utilities Expense'), ('5206', 'Cost of Sales')], max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('guideline', models.TextField(blank=True, null=True)),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3_account', to='acc_codes.accountlevel2')),
            ],
            options={
                'verbose_name': 'AccountLevel3',
                'verbose_name_plural': 'AccountLevel3s',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_account', models.CharField(max_length=3)),
                ('detailed_account', models.CharField(blank=True, max_length=2, null=True)),
                ('guideline', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('super_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_codes.accountlevel3')),
            ],
            options={
                'ordering': ['super_account', 'sub_account', 'detailed_account'],
            },
        ),
    ]
