# Generated by Django 5.1.4 on 2025-01-08 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('guideline', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AccountLevel1',
                'verbose_name_plural': 'AccountLevel1s',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('guideline', models.TextField(blank=True, null=True)),
                ('balance', models.IntegerField(choices=[(1, 'Dr'), (2, 'Cr')])),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_accounts', to='acc_codes.accountlevel1')),
            ],
            options={
                'verbose_name': 'AccountLevel2',
                'verbose_name_plural': 'AccountLevel2s',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountLevel3',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('guideline', models.TextField(blank=True, null=True)),
                ('balance', models.IntegerField(choices=[(1, 'Dr'), (2, 'Cr')])),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3_accounts', to='acc_codes.accountlevel2')),
            ],
            options={
                'verbose_name': 'AccountLevel3',
                'verbose_name_plural': 'AccountLevel3s',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_account', models.CharField(max_length=2)),
                ('detailed_account', models.CharField(blank=True, max_length=2, null=True)),
                ('balance_adjustment', models.IntegerField(blank=True, choices=[(1, 'Dr'), (2, 'Cr')], null=True)),
                ('guideline', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
                ('level3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='acc_codes.accountlevel3')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['level3', 'sub_account', 'detailed_account'],
            },
        ),
    ]
