# Generated by Django 5.1.4 on 2025-01-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_account',
            field=models.CharField(max_length=2),
        ),
    ]
