# Generated by Django 5.1.4 on 2025-01-08 08:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('user_owned', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance_adjustment',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='accountlevel2',
            name='level1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2', to='acc_codes.accountlevel1'),
        ),
        migrations.AlterField(
            model_name='accountlevel3',
            name='level2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3', to='acc_codes.accountlevel2'),
        ),
    ]
