# Generated by Django 5.1.4 on 2025-01-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
