# Generated by Django 5.1.4 on 2025-01-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_codes', '0002_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
