# Generated by Django 5.1.4 on 2025-01-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc_books', '0001_initial'),
        ('acc_codes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intra_month_ref', models.IntegerField(blank=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=9, unique=True)),
                ('has_receipt', models.BooleanField(default=False)),
                ('shop', models.IntegerField(blank=True, choices=[(1, 'まいばすけっと'), (2, 'OK')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='acc_books.book')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['date', 'intra_month_ref'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.IntegerField(choices=[(1, 'Dr'), (2, 'Cr')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='acc_codes.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['entry_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('date', 'intra_month_ref'), name='unique_intra_month_ref'),
        ),
    ]
