# Generated by Django 5.1.4 on 2025-01-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_entry_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shop',
            field=models.IntegerField(blank=True, choices=[(1, 'まいばすけっと'), (2, 'OK')], null=True),
        ),
    ]
