# Generated by Django 5.1.4 on 2025-01-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_book_record_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='guideline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
