# Generated by Django 5.1.4 on 2025-01-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_book_guideline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='abbr',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
