# Generated by Django 5.1.4 on 2025-01-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_alter_transaction_book_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ref',
        ),
        migrations.AddField(
            model_name='transaction',
            name='intra_date_ref',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
