# Generated by Django 5.1.4 on 2025-01-08 08:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('user_owned', django.db.models.manager.Manager()),
            ],
        ),
    ]
