# Generated by Django 5.1.4 on 2025-01-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='record_count',
        ),
    ]
