# Generated by Django 5.1.4 on 2025-01-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_books', '0002_alter_book_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
