# Generated by Django 5.1.4 on 2025-01-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_books', '0002_remove_book_record_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currency_sign',
            field=models.CharField(default='$', max_length=1),
        ),
    ]
